### ISSUE TITLE
Aggregation Attribute doesn't not allow for UTF8 character 

### ISSUE THREAD

**Issue by vdeparday** [AIFDR/inasafe#1153]
Using QGIS 2.4, InaSAFE 2.1 from the QGIS repo

During the workshop in Haiti, we tried to use an attribute for aggregation layer that has City name that contains french characters including accent and it is generating an error (see stacktrace below). If we change it to a column with only numbers then it works but it is not very helpful as it is just numbers and not the actual city names.

We should support all UTF8 characters for the aggregation attribute. 

Stacktrace

Traceback (most recent call last):
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe_qgis/widgets/dock.py", line 1677, in aggregate
    self.post_process()
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe_qgis/widgets/dock.py", line 1692, in post_process
    self.completed()
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe_qgis/widgets/dock.py", line 1482, in completed
    self.analysis_error(e, self.tr('Error loading impact layer.'))
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe_qgis/widgets/dock.py", line 1461, in analysis_error
    self.show_error_message(message)
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe_qgis/widgets/dock.py", line 311, in show_error_message
    message=error_message)
  File "/Users/viv/.qgis2/python/plugins/inasafe/third_party/pydispatch/dispatcher.py", line 349, in send
    **named
  File "/Users/viv/.qgis2/python/plugins/inasafe/third_party/pydispatch/robustapply.py", line 47, in robustApply
    return receiver(*arguments, **named)
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe_qgis/widgets/message_viewer.py", line 188, in error_message_event
    self.dynamic_message_event(sender, message)
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe_qgis/widgets/message_viewer.py", line 206, in dynamic_message_event
    self.show_messages()
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe_qgis/widgets/message_viewer.py", line 250, in show_messages
    html = message.to_html(in_div_flag=True)
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe/messaging/error_message.py", line 260, in to_html
    return self._render().to_html(in_div_flag=in_div_flag)
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe/messaging/error_message.py", line 191, in _render
    items.add(d)
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe/messaging/item/abstract_list.py", line 71, in add
    self.items.append(PlainText(item))
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe/messaging/item/text.py", line 120, in __init__
    self.text = str(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 1: ordinal not in range(128)

**Comment by akbargumbira** [comment]
This is fixed here https://github.com/AIFDR/inasafe/pull/1674

**Comment by akbargumbira** [comment]
I merged the PR. Closing this
