### ISSUE TITLE
Minimum needs error on start

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1358]
I didnt have a chance to investigate yet, but on my system, I get this when starting QGIS:

```
Couldn't load plugin inasafe-dev due an error when calling its classFactory() method


Traceback (most recent call last):
  File "/usr/local/qgis-master/share/qgis/python/qgis/utils.py", line 208, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/timlinux/.qgis2/python/plugins/inasafe-dev/__init__.py", line 30, in classFactory
    from safe_qgis.plugin import Plugin
  File "/usr/local/qgis-master/share/qgis/python/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.qgis2/python/plugins/inasafe-dev/safe_qgis/__init__.py", line 89, in 
    from safe_qgis.utilities.defaults import get_defaults
  File "/usr/local/qgis-master/share/qgis/python/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.qgis2/python/plugins/inasafe-dev/safe_qgis/__init__.py", line 102, in 
    minimum_needs.get_needs_parameters())
  File "/home/timlinux/.qgis2/python/plugins/inasafe-dev/safe_qgis/tools/minimum_needs/needs_profile.py", line 146, in get_needs_parameters
    for resource in self.minimum_needs['resources']:
TypeError: string indices must be integers

```

Just logging it here for now.

**Comment by timlinux** [comment]
Can we close this?

**Comment by ismailsunni** [comment]
I think so. Closing it.
