### ISSUE TITLE
Python error on first load

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1393]
# Problem

Opening QGIS with no plugins loaded, then enabling InaSAFE in the plugin manager I get this:

```python
Couldn't load plugin inasafe-dev due an error when calling its classFactory() method


Traceback (most recent call last):
  File "/usr/local/qgis-2.4/share/qgis/python/qgis/utils.py", line 204, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/timlinux/.qgis2/python/plugins/inasafe-dev/__init__.py", line 30, in classFactory
    from safe_qgis.plugin import Plugin
  File "/usr/local/qgis-2.4/share/qgis/python/qgis/utils.py", line 454, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.qgis2/python/plugins/inasafe-dev/safe_qgis/__init__.py", line 90, in 
    from safe_qgis.utilities.defaults import get_defaults
ImportError: cannot import name get_defaults
```

# CC

@cchristelis

**Comment by akbargumbira** [comment]
closing this - not relevant anymore
