### ISSUE TITLE
Python Error when installing InaSAFE 2.2 from Qgis Plugin

### ISSUE THREAD

**Issue by fredychandra** [AIFDR/inasafe#1432]
I got this error message when I wanted to install InaSAFE from QGIS Repo

```
Couldn't load plugin inasafe due an error when calling its classFactory() method

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISCH~1/apps/qgis/./python\qgis\utils.py", line 204, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/chandf/.qgis2/python/plugins\inasafe\__init__.py", line 25, in classFactory
    from safe_qgis.plugin import Plugin
  File "C:/PROGRA~1/QGISCH~1/apps/qgis/./python\qgis\utils.py", line 454, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/chandf/.qgis2/python/plugins\inasafe\safe_qgis\__init__.py", line 84, in 
    from safe_qgis.utilities.defaults import get_defaults
  File "C:/PROGRA~1/QGISCH~1/apps/qgis/./python\qgis\utils.py", line 454, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\chandf\.qgis2\python\plugins\inasafe\safe_qgis\__init__.py", line 92, in 
    minimum_needs = NeedsProfile()
  File "C:\Users\chandf\.qgis2\python\plugins\inasafe\safe_qgis\tools\minimum_needs\needs_profile.py", line 41, in __init__
    self.load()
  File "C:\Users\chandf\.qgis2\python\plugins\inasafe\safe_qgis\tools\minimum_needs\needs_profile.py", line 50, in load
    profiles = self.get_profiles()
  File "C:\Users\chandf\.qgis2\python\plugins\inasafe\safe_qgis\tools\minimum_needs\needs_profile.py", line 132, in get_profiles
    for file_name in listdir(path_name):
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\chandf\\.qgis2\\python\\plugins\\inasafe\\safe_qgis\\tools\\minimum_needs/../../../files/minimum_needs/*.*'


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.4.0-Chugiak Chugiak, 8fdd08a

Python path: ['C:/PROGRA~1/QGISCH~1/apps/qgis/./python/plugins\\processing', 'C:/PROGRA~1/QGISCH~1/apps/qgis/./python', u'C:/Users/chandf/.qgis2/python', u'C:/Users/chandf/.qgis2/python/plugins', 'C:/PROGRA~1/QGISCH~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISCH~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISCH~1\\bin', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'C:\\Users\\chandf\\.qgis2\\python\\plugins\\MetaSearch\\ext-libs', 'C:\\PROGRA~1\\QGISCH~1\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\Users\\chandf\\.qgis2\\python\\plugins\\inasafe', 'C:\\Users\\chandf\\.qgis2\\python\\plugins\\inasafe\\safe_extras', 'C:\\Users\\chandf\\.qgis2\\python\\plugins\\inasafe', 'C:\\Users\\chandf\\.qgis2\\python\\plugins\\inasafe', 'C:\\Users\\chandf\\.qgis2\\python\\plugins\\inasafe', 'C:\\Users\\chandf\\.qgis2\\python\\plugins\\inasafe', 'C:\\Users\\chandf\\.qgis2\\python\\plugins\\inasafe', 'C:\\Users\\chandf\\.qgis2\\python\\plugins\\inasafe', 'C:\\Users\\chandf\\.qgis2\\python\\plugins\\inasafe']
```

**Comment by akbargumbira** [comment]
closing this - not relevant anymore
