### ISSUE TITLE
Python error when selecting an openlayers plugin layer

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1496]
# Problem

When clicking on the stamen watercolour layer from the openlayers plugin I get this:

```python
An error has occured while executing Python code:


Traceback (most recent call last):
  File "/home/timlinux/.qgis2/python/plugins/inasafe-dev/safe/gui/widgets/dock.py", line 1427, in layer_changed
    self.show_error_message(error_message)
  File "/home/timlinux/.qgis2/python/plugins/inasafe-dev/safe/gui/widgets/dock.py", line 310, in show_error_message
    self.hide_busy()
  File "/home/timlinux/.qgis2/python/plugins/inasafe-dev/safe/gui/widgets/dock.py", line 1268, in hide_busy
    if self.analysis.runner:
AttributeError: 'NoneType' object has no attribute 'runner'


Python version:
2.7.8 (default, Nov 10 2014, 08:19:18) 
[GCC 4.9.2 20141101 (Red Hat 4.9.2-1)]


QGIS version:
2.7.0-Master Master, 2c773a7

Python path: ['/usr/local/qgis-master/share/qgis/python/plugins/processing', '/usr/local/qgis-master/share/qgis/python', u'/home/timlinux/.qgis2/python', u'/home/timlinux/.qgis2/python/plugins', '/usr/local/qgis-master/share/qgis/python/plugins', '/usr/lib/python2.7/site-packages/pycharm-debug.egg', '/usr/local/qgis-master/share/qgis/python', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib64/python2.7/site-packages/wx-2.8-gtk2-unicode', '/usr/lib/python2.7/site-packages', '/home/timlinux/.qgis2/python/plugins/inasafe-dev', '/home/timlinux/.qgis2/python/plugins/inasafe-dev/safe_extras/parameters', '/home/timlinux/.qgis2/python/plugins/inasafe-dev/safe_extras', '/usr/local/qgis-master/share/qgis/python/plugins/fTools/tools', '/home/timlinux/.qgis2/python/plugins/inasafe', '/home/timlinux/.qgis2/python/plugins/MetaSearch/ext-libs', '/home/timlinux/.qgis2/python/plugins/SGDiagramDownloader/third_party', '/home/timlinux/.qgis2/python/plugins/StreamFeatureExtractor/third_party', '.', '/home/timlinux/dev/python/inasafe_data/test', u'/home/timlinux/dev/python/QGISSnippets']
```

# Proposed solution

Please add a check that the runner is instantiated before trying to refer to its properties.

**Comment by akbargumbira** [comment]
I found this some earlier. Apparently, now hide_busy is connected to the runner, which some function does not really hae a runner (impact calculator). I changed some of them to just call disable_busy_cursor if that's the case..

**Comment by ismailsunni** [comment]
Hi @timlinux 

I think you tried on 'not-to-updated' version of InaSAFE. I have fixed the similar issue, see #1473 

And based on the error message, it's not the latest source code. See https://github.com/AIFDR/inasafe/blob/develop/safe/gui/widgets/dock.py#L1268

Can you try it again with the latest inasafe ?

**Comment by timlinux** [comment]
OK will test with develop, thanks!

**Comment by timlinux** [comment]
Confirmed this works for me now in develop
