### ISSUE TITLE
Running this specific shakemap throws Python error

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#1513]
# Problem
Running the shakemap with ID 20140204091756 throws this:
```
ERROR:InaSAFE Realtime:Process event failed
Traceback (most recent call last):
  File "realtime/make_map.py", line 147, in <module>
    process_event(working_dir=working_dir, locale=locale_option)
  File "realtime/make_map.py", line 107, in process_event
    shake_event.render_map(force_flag)
  File "/home/akbar/dev/python/inasafe-dev/realtime/shake_event.py", line 1386, in render_map
    location_info = self.event_info()
  File "/home/akbar/dev/python/inasafe-dev/realtime/shake_event.py", line 1528, in event_info
    event_dict = self.event_dict()
  File "/home/akbar/dev/python/inasafe-dev/realtime/shake_event.py", line 1599, in event_dict
    self.sorted_impacted_cities()
  File "/home/akbar/dev/python/inasafe-dev/realtime/shake_event.py", line 759, in sorted_impacted_cities
    layer = self.local_cities_memory_layer()
  File "/home/akbar/dev/python/inasafe-dev/realtime/shake_event.py", line 644, in local_cities_memory_layer
    cities = self.local_city_features()
  File "/home/akbar/dev/python/inasafe-dev/realtime/shake_event.py", line 589, in local_city_features
    mmi = float(value)
TypeError: float() argument must be a string or a number
```

# CC
@timlinux

**Comment by akbargumbira** [comment]
Fixed here https://github.com/AIFDR/inasafe/pull/1516
