### ISSUE TITLE
Bug: v3.0 python error generated by polygon flood on building IF

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1672]
# problem
A python error occurs when running the flood impact on buildings (experimental) IF

Data: jakarta flood polygons 2013 & OSM jakarta buildings

# error message
```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe\utilities\analysis.py", line 905, in run_aggregator
    self.run_post_processor()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe\utilities\analysis.py", line 921, in run_post_processor
    self.send_analysis_done_signal()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe\utilities\analysis.py", line 278, in send_analysis_done_signal
    message='')
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe_extras\pydispatch\dispatcher.py", line 349, in send
    **named
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe_extras\pydispatch\robustapply.py", line 47, in robustApply
    return receiver(*arguments, **named)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe\gui\widgets\dock.py", line 1166, in completed
    self.wvResults.impact_path = impact_path
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe\gui\widgets\message_viewer.py", line 110, in impact_path
    self.show_report()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe\gui\widgets\message_viewer.py", line 314, in show_report
    self.load_html_file(self.report_path)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe\gui\widgets\message_viewer.py", line 340, in load_html_file
    self.load_html(HTML_FILE_MODE, file_path)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe\gui\widgets\message_viewer.py", line 379, in load_html
    self.loadFinished.disconnect(self.html_loaded_slot)
TypeError: disconnect() failed between 'loadFinished' and 'unislot'


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.6.0-Brighton Brighton, exported

Python path: ['C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISBR~1/apps/qgis/./python', u'C:/Users/AIFDR_ADMIN/.qgis2/python', u'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins', 'C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\bin', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\arcpy', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\ArcToolbox', 'C:\\PROGRA~1\\QGISBR~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISBR~1\\bin', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\\inasafe-dev', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe-dev\\safe_extras\\parameters', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\MetaSearch\\ext-libs', 'C:\\PROGRA~1\\QGISBR~1\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe-dev', 'C:/WorkSpace/InaSAFE Testing']
```
# proposed solution
make it happy :)

**Comment by akbargumbira** [comment]
```
this is code
```

**Comment by akbargumbira** [comment]
Hi @Charlotte-Morgan, I could not replicate this. I will try this on Windows next week

**Comment by akbargumbira** [comment]
Hi @Charlotte-Morgan, I tried this on Windows 7 64bit using the same flood polygon and building data, but I didn't get the errror running it from both the dock and the wizard:

![1](https://cloud.githubusercontent.com/assets/992519/6438207/9a256dd2-c0f9-11e4-9d58-102b26e8c237.PNG)

**Comment by Charlotte-Morgan** [comment]
@akbargumbira - thanks for checking. What about the type error?

**Comment by akbargumbira** [comment]
Yeah, there was no type error, maybe I could try it on your computer?

**Comment by akbargumbira** [comment]
This is fixed in master
