### ISSUE TITLE
Bug : Python error when adding a layer in the map canvas

### ISSUE THREAD

**Issue by Gustry** [AIFDR/inasafe#1685]
With QGIS master, I've this error each time when I'm adding a layer in the map canvas : 
```
An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1470, in layer_changed
    self.show_no_keywords_message()
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1436, in show_no_keywords_message
    self.show_static_message(report)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 280, in show_static_message
    message=message)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe_extras/pydispatch/dispatcher.py", line 349, in send
    **named
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe_extras/pydispatch/robustapply.py", line 47, in robustApply
    return receiver(*arguments, **named)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/message_viewer.py", line 185, in static_message_event
    self.show_messages()
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/message_viewer.py", line 259, in show_messages
    self.load_html(HTML_STR_MODE, string)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/message_viewer.py", line 379, in load_html
    self.loadFinished.disconnect(self.html_loaded_slot)
TypeError: disconnect() failed between 'loadFinished' and 'unislot'
```

**Comment by akbargumbira** [comment]
Hi @Gustry, this ```TypeError: disconnect() failed between 'loadFinished' and 'unislot'``` seems to be everywhere on @Charlotte-Morgan's computer and yours. What is your computer environment? I don't get it here on Ubuntu and QGIS Master compiled an hour ago

**Comment by Gustry** [comment]
Maybe a duplicate #1688
