### ISSUE TITLE
Bug: errors with EQ Building IF in IFW

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1686]
# problem
the following errors are reported for EQ Building function.  InaSAFE 3.0 & Padang earthquake scenario.

1. python error when running EQ impact function using data preloaded in QGIS.

```
An error has occurred while executing Python code:


Traceback (most recent call last):
  File "C:/Users/localadmin/.qgis2/python/plugins\inasafe-dev\safe\gui\tools\wizard_dialog.py", line 2998, in on_pbnNext_released
    self.set_widgets_step_fc_params()
  File "C:/Users/localadmin/.qgis2/python/plugins\inasafe-dev\safe\gui\tools\wizard_dialog.py", line 2700, in set_widgets_step_fc_params
    imfunctions = get_safe_impact_function(imfunc_id)
  File "C:/Users/localadmin/.qgis2/python/plugins\inasafe-dev\safe\utilities\utilities.py", line 366, in get_safe_impact_function
    return get_plugins(function_name)
  File "C:/Users/localadmin/.qgis2/python/plugins\inasafe-dev\safe\impact_functions\core.py", line 212, in get_plugins
    raise RuntimeError(msg)
RuntimeError: No plugin named "EarthQuakeBuildingImpactFunction" was found. List of available plugins is: 
Classified Hazard Building Impact Function,
 ClassifiedHazardBuildingImpactFunction,
 Flood Native Polygon Experimental Function,
 VolcanoBuildingImpact,
 Flood Evacuation Function Vector Hazard,
 EarthquakeBuildingImpactFunction,
 Flood Evacuation Function,
 Classified Hazard Population Impact Function,
 FloodEvacuationFunction,
 FloodRasterRoadsExperimentalFunction2,
 Volcano Building Impact,
 Earthquake Building Impact Function,
 PAGFatalityFunction,
 Flood Vector Roads Experimental Function,
 FloodVectorRoadsExperimentalFunction,
 FloodEvacuationFunctionVectorHazard,
 VolcanoPolygonHazardPopulation,
 Flood Raster Roads Experimental Function,
 FloodNativePolygonExperimentalFunction,
 ITBFatalityFunction,
 ClassifiedHazardPopulationImpactFunction,
 FloodBuildingImpactFunction,
 Continuous Hazard Population Impact Function,
 PAG Fatality Function,
 Flood Building Impact Function,
 Tsunami Evacuation Function,
 ITB Fatality Function,
 ContinuousHazardPopulationImpactFunction,
 Volcano Polygon Hazard Population,
 FloodRasterRoadsExperimentalFunction,
 TsunamiEvacuationFunction


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.6.0-Brighton Brighton, exported

Python path: ['C:/Users/localadmin/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISBR~1/apps/qgis/./python', u'C:/Users/localadmin/.qgis2/python', u'C:/Users/localadmin/.qgis2/python/plugins', 'C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\python_dateutil-2.1-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISBR~1\\bin', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'C:/Users/localadmin/.qgis2/python/plugins\\inasafe-dev', 'C:\\Users\\localadmin\\.qgis2\\python\\plugins\\inasafe-dev\\safe_extras\\parameters', 'C:\\Users\\localadmin\\.qgis2\\python\\plugins', 'C:\\Users\\localadmin\\.qgis2\\python\\plugins\\MetaSearch\\ext-libs', 'C:\\PROGRA~1\\QGISBR~1\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\Users\\localadmin\\.qgis2\\python\\plugins\\inasafe', 'C:\\Users\\localadmin\\.qgis2\\python\\plugins\\inasafe']
```
2. the wizard implies that earthquake hazard data can be read as raster and vector. I think it should only run on continuous raster??

# proposed solution
make it happy

**Comment by akbargumbira** [comment]
1. Fixed
2. Yes, it should only work for raster continuos with mmi value in each pixel

Will also backport this to master

**Comment by akbargumbira** [comment]
Hi @Charlotte-Morgan, I fixed this both in develop and master. I am closing this
