### ISSUE TITLE
Bug: eeeeek

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1713]
```python
Couldn't load plugin inasafe due an error when calling its initGui() method


Traceback (most recent call last):
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python\qgis\utils.py", line 217, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\plugin.py", line 392, in initGui
    self.dock_widget = Dock(self.iface)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 191, in __init__
    self.read_settings()  # get_project_layers called by this
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 404, in read_settings
    height_ratio = maximum_height / pixmap.height()
ZeroDivisionError: float division by zero


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.6.0-Brighton Brighton, exported

Python path: ['C:/PROGRA~1/QGISBR~1/apps/qgis/./python', u'C:/Users/AIFDR_ADMIN/.qgis2/python', u'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins', 'C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\bin', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\arcpy', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\ArcToolbox', 'C:\\PROGRA~1\\QGISBR~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISBR~1\\bin', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\\inasafe', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe\\safe_extras\\parameters', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins']
```

**Comment by adissadis** [comment]
I also got this error same with @Charlotte-Morgan 

But my friends who copied my inasafe files didn't got any error like this.

# My Platform
Windows 7 64bit 
QGIS 2.6 (previously i have QGIS 1.8 and 2.4 but i already uninstalled)

# Sucessfull platform (who success run this InaSAFE from my copied files)
Windows 7 32 bit
QGIS 2.6 (but she also have QGIS 1.8)

Windows 8 64bit
QGIS 2.6 (and he have QGIS 2.4 also)


# Screenshot
![inasafe_7](https://cloud.githubusercontent.com/assets/2520159/6481627/bc36ec86-c291-11e4-992a-8980d6f9fef6.png)

**Comment by Charlotte-Morgan** [comment]
thank @adissadis - this was a brand new package that Tim put together for me :(
