### ISSUE TITLE
Bug: Load Test Data

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1795]
```
 An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\plugin.py", line 550, in add_test_layers
    from safe.test.utilities import load_standard_layers
  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named test.utilities
```

**Comment by akbargumbira** [comment]
This happens as we don't package ```safe.test.*``` modules in the release.sh script (when we package InaSAFE for a release) (the load_standard_layers function and the test data layers are all there) cc @timlinux @gustry
