### ISSUE TITLE
Options dialog raises unhandled error

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1830]
# Problem

In current develop, if I click on options for flood on population I get 

```python
An error has occured while executing Python code:


Traceback (most recent call last):
  File "/Users/timlinux/.qgis2/python/plugins/,/safe/gui/widgets/dock.py", line 835, in on_toolFunctionOptions_clicked
    dialog.build_form(self.impact_function_parameters)
  File "/Users/timlinux/.qgis2/python/plugins/,/safe/impact_statistics/function_options_dialog.py", line 125, in build_form
    self.build_minimum_needs_form(value)
  File "/Users/timlinux/.qgis2/python/plugins/,/safe/impact_statistics/function_options_dialog.py", line 141, in build_minimum_needs_form
    parameter_container = ParameterContainer(parameters, extra_parameters)
  File "/Users/timlinux/.qgis2/python/plugins/,/safe_extras/parameters/qt_widgets/parameter_container.py", line 68, in __init__
    parameter_widget = self.qt4_parameter_factory.get_widget(parameter)
  File "/Users/timlinux/.qgis2/python/plugins/,/safe_extras/parameters/qt_widgets/qt4_parameter_factory.py", line 62, in get_widget
    return self.dict_widget[class_name](parameter)
  File "/Users/timlinux/.qgis2/python/plugins/,/safe/common/resource_parameter_widget.py", line 33, in __init__
    super(ResourceParameterWidget, self).__init__(parameter, parent)
  File "/Users/timlinux/.qgis2/python/plugins/,/safe_extras/parameters/qt_widgets/float_parameter_widget.py", line 26, in __init__
    super(FloatParameterWidget, self).__init__(parameter, parent)
  File "/Users/timlinux/.qgis2/python/plugins/,/safe_extras/parameters/qt_widgets/numeric_parameter_widget.py", line 29, in __init__
    super(NumericParameterWidget, self).__init__(parameter, parent)
  File "/Users/timlinux/.qgis2/python/plugins/,/safe_extras/parameters/qt_widgets/generic_parameter_widget.py", line 34, in __init__
    self._help_text_label = QLabel(self._parameter.help_text)
TypeError: arguments did not match any overloaded call:
  QLabel(QWidget parent=None, Qt.WindowFlags flags=0): argument 1 has unexpected type 'QPyNullVariant'
  QLabel(QString, QWidget parent=None, Qt.WindowFlags flags=0): argument 1 has unexpected type 'QPyNullVariant'


Python version:
2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]


QGIS version:
2.8.1-Wien Wien, 

Python path: ['/Users/timlinux/.qgis2/python/plugins/processing', '/Applications/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/timlinux/.qgis2/python', u'/Users/timlinux/.qgis2/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/numpy-override', '/Library/Python/2.7/site-packages/matplotlib-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', u'/Users/timlinux/.qgis2//python', '/Users/timlinux/.qgis2/python/plugins/,', '/Users/timlinux/.qgis2/python/plugins/,/safe_extras/parameters', '/Users/timlinux/.qgis2/python/plugins', '/Users/timlinux/.qgis2/python/plugins/,/safe_extras', '/Users/timlinux/.qgis2/python/plugins/SGDiagramDownloader/third_party', '/Users/timlinux/.qgis2/python/plugins/StreamFeatureExtractor/third_party', '/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools']
```

Scenario:

```
[Continuous Flood]
exposure = ../.qgis2/python/plugins/,/safe/test/data/exposure/pop_binary_raster_20_20.asc
hazard = ../.qgis2/python/plugins/,/safe/test/data/hazard/continuous_flood_20_20.asc
function = FloodEvacuationRasterHazardFunction
extent = 106.805951, -6.190212, 106.825874, -6.169946
extent_crs = EPSG:4326


```

# Proposed solution

@Jannes123 can you please investigate?

**Comment by Jannes123** [comment]
@timlinux I am not able to replicate the issue on my machine.  It might be a system dependent bug.
