### ISSUE TITLE
Philippine Minimum Needs profile break when loading layers.

### ISSUE THREAD

**Issue by cchristelis** [AIFDR/inasafe#1893]
## Problem

After pulling from develop today (with Philippine minimum needs profile loaded) I load a project with several layers I get the following error:

```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "/home/christian/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 775, in on_cboFunction_currentIndexChanged
    function = self.impact_function_manager.get(function_id)
  File "/home/christian/.qgis2/python/plugins/inasafe/safe/impact_functions/impact_function_manager.py", line 102, in get
    return impact_functions[0].instance()
  File "/home/christian/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 191, in instance
    return cls()
  File "/home/christian/.qgis2/python/plugins/inasafe/safe/impact_functions/volcanic/volcano_polygon_population/impact_function.py", line 46, in __init__
    self.parameters = add_needs_parameters(self.parameters)
  File "/home/christian/.qgis2/python/plugins/inasafe/safe/gui/tools/minimum_needs/needs_profile.py", line 34, in add_needs_parameters
    parameters['minimum needs'] = minimum_needs.get_needs_parameters()
  File "/home/christian/.qgis2/python/plugins/inasafe/safe/gui/tools/minimum_needs/needs_profile.py", line 211, in get_needs_parameters
    if resource[element] is not None and '.' in resource[element]:
TypeError: argument of type 'float' is not iterable


Python version:
2.7.8 (default, Apr 15 2015, 09:26:43) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)]
```

## Proposed Solution

Fix.

**Comment by cchristelis** [comment]
Hi @Jannes123, please have a look at this asap if you can.

**Comment by Jannes123** [comment]
@cchristelis I am unable to replicate the issue at the moment
