### ISSUE TITLE
Python errors when configuring Categorical Thresholds

### ISSUE THREAD

**Issue by wonder-sk** [AIFDR/inasafe#2028]
I try to use ContinuousHazardPopulationFunction (with InaSAFE test data - earthquake in Padang 2009 / global population raster). When I open options dialog for the IF, I am able to configure categorical thresholds. There are however few issues with the dialog:

- if I configure fewer or more than three entries:
```
Traceback (most recent call last):
  File "/home/martin/.qgis2/python/plugins/inasafe/safe/impact_statistics/function_options_dialog.py", line 259, in accept
    self._result = self.parse_input(self.values)
  File "/home/martin/.qgis2/python/plugins/inasafe/safe/impact_statistics/function_options_dialog.py", line 244, in parse_input
    result[name] = value()
  File "/home/martin/.qgis2/python/plugins/inasafe/safe_extras/parameters/qt_widgets/parameter_container.py", line 107, in get_parameters
    parameter = parameter_widget.get_parameter()
  File "/home/martin/.qgis2/python/plugins/inasafe/safe_extras/parameters/qt_widgets/input_list_parameter_widget.py", line 170, in get_parameter
    self._parameter.value = self._value_cache
  File "/home/martin/.qgis2/python/plugins/inasafe/safe_extras/parameters/input_list_parameter.py", line 46, in value
    self.check_length(value)
  File "/home/martin/.qgis2/python/plugins/inasafe/safe_extras/parameters/collection_parameter.py", line 176, in check_length
    raise CollectionLengthError(message)
CollectionLengthError: 2 elements were found in the collection "Categorical Thresholds", there should be at least 3 element(s) and no more than 3 element(s).
```
- if I enter by mistake a non-numerical value and click Add:
```
Traceback (most recent call last):
  File "/home/martin/.qgis2/python/plugins/inasafe/safe_extras/parameters/qt_widgets/input_list_parameter_widget.py", line 138, in on_add_button_click
    raise err
ValueError: Expecting element type of float
```
- the defaults are 0.34, 0.67, 1. If I remove value 1 and add 0.2, the new value gets to the bottom of the list. Later when try to run the function, it fails with error below. Maybe the list should be kept sorted automatically?
```
The following problem(s) were encountered whilst running the analysis.
FunctionParametersError

Diagnostics (click for details)
In file "/home/martin/.qgis2/python/plugins/inasafe/safe/utilities/impact_calculator_thread.py", line 169, in run
  check_integrity=self._check_integrity)
In file "/home/martin/.qgis2/python/plugins/inasafe/safe/engine/core.py", line 171, in calculate_impact 
  result_layer = impact_function.run()
In file "/home/martin/.qgis2/python/plugins/inasafe/safe/impact_functions/generic/continuous_hazard_population/impact_function.py", line 145, in run
  'Each threshold should be larger than the previous.')
```

Using latest code from develop branch.

**Comment by timlinux** [comment]
Hi @lucernae 

I had in mind something more like this:

![parametersclasses 8](https://cloud.githubusercontent.com/assets/178003/8098286/5ae418b2-1018-11e5-99b4-e5145fa61f99.png)

**Comment by lucernae** [comment]
@timlinux 
Actually, this is what I have right now:

![image](https://cloud.githubusercontent.com/assets/831865/8099249/4c833a80-1024-11e5-8e24-f753a09d8862.png)

I am using GroupParameter like what I did in Age postprocessor, and in the code side we can add custom validation in the GroupParameter.

Is this ok?

Btw, we also have Tsunami Thresholds which can contains more than one thresholds. So I keep it using InputListParameter widget

**Comment by timlinux** [comment]
That looks much better thanks.

> Btw, we also have Tsunami Thresholds which can contains more than one thresholds. So I keep it using InputListParameter widget

It would still ultimately be nicer to have a proper parameters widget implemented for tsunami since one of our design goals is to make intuitive, self explanatory UIs
