### ISSUE TITLE
Upgrading from 3 to 3.1.2 gives python error

### ISSUE THREAD

**Issue by kateregga1** [AIFDR/inasafe#2143]
Couldn't load plugin inasafe due to an error when calling its classFactory() method

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/geoffrey/.qgis2/python/plugins/inasafe/__init__.py", line 86, in classFactory
    from safe.plugin import Plugin
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/geoffrey/.qgis2/python/plugins/inasafe/safe/plugin.py", line 37, in 
    from safe.common.version import release_status
ImportError: cannot import name release_status
```

**Comment by ismailsunni** [comment]
hi @kateregga1 
Can you try to disable InaSAFE, then restart QGIS, then enable InaSAFE again?

**Comment by kateregga1** [comment]
@ismailsunni 

Restarting QGIS solved the problem

**Comment by ismailsunni** [comment]
Great
