### ISSUE TITLE
Flood on roads fails

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2153]
Using Tanzania data on window 8 64 bit with QGIS 2.8.2 and InaSAFE 3.1.2 and trying to do a flood on roads I got the following error:

```
Traceback (most recent call last):
  File "C:/Users/User/.qgis2/python/plugins\inasafe\safe\utilities\analysis.py", line 923, in run_aggregator
    self.aggregator.aggregate(impact_layer)
  File "C:/Users/User/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 553, in aggregate
    qgis_impact_layer, safe_impact_layer)
  File "C:/Users/User/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 660, in _aggregrate_vector_impact
    self._aggregate_line_impact(safe_impact_layer)
  File "C:/Users/User/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 950, in _aggregate_line_impact
    res['OUTPUT'], 'split aggregation', 'ogr')
TypeError: 'NoneType' object has no attribute '__getitem__'
Aggregation error occurred
```

**Comment by ismailsunni** [comment]
**UPDATE**
The error is caused by when run the analysis in QGIS, it couldn't find the algorithm `qgis:intersection` in Processing.
The strange thing is, if we run the test in PyCharm, that algorithm is found.

Is that even possible?
