### ISSUE TITLE
Traceback when running continuous flood on population

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2180]
Using standard test layers I get this:

```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 777, in on_cboFunction_currentIndexChanged
    function = self.impact_function_manager.get(function_id)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/impact_function_manager.py", line 101, in get
    return impact_functions[0].instance()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 228, in instance
    return cls()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/inundation/flood_raster_population/impact_function.py", line 47, in __init__
    self.parameters = add_needs_parameters(self.parameters)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/tools/minimum_needs/needs_profile.py", line 36, in add_needs_parameters
    parameters['minimum needs'] = minimum_needs.get_needs_parameters()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/tools/minimum_needs/needs_profile.py", line 268, in get_needs_parameters
    prov_parameter.value = self.provenance
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe_extras/parameters/generic_parameter.py", line 180, in value
    self._check_type(value)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe_extras/parameters/generic_parameter.py", line 157, in _check_type
    raise TypeError(message)
TypeError: The type of the _value [] does match with the expected type of the parameter [[, ]].

```

**Comment by ismailsunni** [comment]
Hi @timlinux 
I tried with QGIS 2.8.3 in Ubuntu, and it is fine. Can you tell me what's your environment?

**Comment by timlinux** [comment]
It works for me now on both OS X (where original issue was encountered) and Fedora 22...closing....
