### ISSUE TITLE
Parameters exception when setting classified flood on population in dock

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2222]
Using the standard test layers from the developer mode add test layers option I get this for *clasiffied* flood on population.

```
Traceback (most recent call last):
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1176, in draw_rubber_bands
    self.show_next_analysis_extent()  # green
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2042, in show_next_analysis_extent
    valid, extents = self.validate_extents()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2114, in validate_extents
    analysis = self.prepare_analysis()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1313, in prepare_analysis
    self.get_function_id())
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/impact_function_manager.py", line 101, in get
    return impact_functions[0].instance()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 228, in instance
    return cls()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/generic/classified_raster_population/impact_function.py", line 62, in __init__
    self.parameters = add_needs_parameters(self.parameters)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/tools/minimum_needs/needs_profile.py", line 36, in add_needs_parameters
    parameters['minimum needs'] = minimum_needs.get_needs_parameters()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/tools/minimum_needs/needs_profile.py", line 268, in get_needs_parameters
    prov_parameter.value = self.provenance
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe_extras/parameters/generic_parameter.py", line 180, in value
    self._check_type(value)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe_extras/parameters/generic_parameter.py", line 157, in _check_type
    raise TypeError(message)
TypeError: The type of the _value [] does match with the expected type of the parameter [[, ]].
```

# Proposed solution

@lucernae please check through the parameters code and see what is going on here

**Comment by timlinux** [comment]
@lucernae any update on this?

**Comment by timlinux** [comment]
This error is raised if the MinimumNeedsProfile has no provenance
