### ISSUE TITLE
Python Error on Show Next Analysis Extent

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#2281]
Problem
-----------
- Opening two layers with CRS EPSG=32618 or 3857
- Wait..
- Python error comes out:
```
Terjadi kesalahan ketika menjalankan kode Python:


Traceback (most recent call last):
  File "/home/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe/gui/widgets/dock.py", line 1173, in draw_rubber_bands
    self.show_next_analysis_extent()  # green
  File "/home/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe/gui/widgets/dock.py", line 2122, in show_next_analysis_extent
    current_text = self.wvResults.page_to_text()
  File "/home/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe/gui/widgets/message_viewer.py", line 275, in page_to_text
    return my_message.to_text()
  File "/home/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe/messaging/message.py", line 107, in to_text
    message += m.to_text()
  File "/home/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe/messaging/message.py", line 107, in to_text
    message += m.to_text()
  File "/home/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe/messaging/item/table.py", line 106, in to_text
    raise NotImplementedError('Please don\'t use this class directly')
NotImplementedError: Please don't use this class directly


Versi Python:
2.7.6 (default, Jun 22 2015, 18:01:27) 
[GCC 4.8.2]


Versi QGIS:
2.8.3-Wien Wien, exported

Jalur (path) Python: ['/home/ismailsunni/.qgis2/python/plugins/processing', '/usr/share/qgis/python', u'/home/ismailsunni/.qgis2/python', u'/home/ismailsunni/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/local/lib/python2.7/dist-packages/pycharm-debug.egg', '/usr/local/lib/python2.7/dist-packages/overpass-0.1.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/geojson-1.0.9-py2.7.egg', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/PIL', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', u'/home/ismailsunni/.qgis2//python', '/home/ismailsunni/.qgis2/python/plugins/mmqgis/forms', '/home/ismailsunni/.qgis2/python/plugins/inasafe-dev', '/home/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe_extras/parameters', '/home/ismailsunni/.qgis2/python/plugins', '/home/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe_extras', '/usr/share/qgis/python/plugins/fTools/tools', '/home/ismailsunni/.qgis2/python/plugins/SGDiagramDownloader/third_party']
```
- After closing the python error window, QGIS closes.

Another scenario:
- When I reproject each layer to EPSG 4326, no error found.
- When I open first layer with EPSG 4326, and load second layer with EPSG 3857, no error found. May be becaue it's reprojected on the fly to 4326.
- When I open the first layer with EPSF 32618, and later load the second layer with EPSG 4326, the same error founds.

Perhaps, if QGIS does not work on CRS 4326, it will give the error.

**Comment by ismailsunni** [comment]
It will be fixed by @timlinux PR in #2287 We can close this after the the PR have been merged.
