### ISSUE TITLE
Failure to create flood keywords using Keywords Wizard

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2286]
# Problem

I am trying to make keywords for a simple flood polygon layer. At the end of the process of using the keywords wizard, I get the following error:

```
Traceback (most recent call last):
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/tools/wizard_dialog.py", line 3607, in on_pbnNext_released
    self.save_current_keywords()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/tools/wizard_dialog.py", line 4255, in save_current_keywords
    self.dock.get_layers()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1027, in get_layers
    self.draw_rubber_bands()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1173, in draw_rubber_bands
    self.show_next_analysis_extent()  # green
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2122, in show_next_analysis_extent
    current_text = self.wvResults.page_to_text()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/message_viewer.py", line 275, in page_to_text
    return my_message.to_text()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/messaging/message.py", line 107, in to_text
    message += m.to_text()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/messaging/message.py", line 107, in to_text
    message += m.to_text()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/messaging/item/table.py", line 106, in to_text
    raise NotImplementedError('Please don\'t use this class directly')
NotImplementedError: Please don't use this class directly
```

**Comment by timlinux** [comment]
To fix we need to implement the virtual ``to_text`` method to messaging table class and the row and cell classes.

**Comment by ismailsunni** [comment]
Another similar issue #2281
