### ISSUE TITLE
[Bug] Python Error when analysis extent is not automatically setup

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#2292]
# Problem
Python error when analysis extent is not automatically setup

# Detail
So i found this python error when i run InaSAFE EQ analysis with using '**user defined bounding box**' and then i open new project/new qgis with other hazard (flood hazard). And when i add both hazard and exposure data, a window popped out and said i got python error. 

What I think it's because the user defined bounding box. When the user select their own area of interest using user defined bounding box area for analysis and then they analysis other hazard in different area, the bounding box still set with previous extent. Please take a look at screenshot below:
![image](https://cloud.githubusercontent.com/assets/2520159/9571881/88081504-4fcf-11e5-949c-6e98c3094e8e.png)
Notice that extent analysis area still set up in previous extent even i already restart QGIS.

# Error Screenshots
![image](https://cloud.githubusercontent.com/assets/2520159/9571855/eed7fdf4-4fce-11e5-92fb-d300cfb171ff.png)

# Traceback detail
```
Traceback (most recent call last):
  File "C:/Users/Sony/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1027, in get_layers
    self.draw_rubber_bands()
  File "C:/Users/Sony/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1173, in draw_rubber_bands
    self.show_next_analysis_extent()  # green
  File "C:/Users/Sony/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 2122, in show_next_analysis_extent
    current_text = self.wvResults.page_to_text()
  File "C:/Users/Sony/.qgis2/python/plugins\inasafe\safe\gui\widgets\message_viewer.py", line 275, in page_to_text
    return my_message.to_text()
  File "C:/Users/Sony/.qgis2/python/plugins\inasafe\safe\messaging\message.py", line 107, in to_text
    message += m.to_text()
  File "C:/Users/Sony/.qgis2/python/plugins\inasafe\safe\messaging\message.py", line 107, in to_text
    message += m.to_text()
  File "C:/Users/Sony/.qgis2/python/plugins\inasafe\safe\messaging\item\table.py", line 106, in to_text
    raise NotImplementedError('Please don\'t use this class directly')
NotImplementedError: Please don't use this class directly
```

# How to produce this error
1. Run InaSAFE analysis with 'user defined analysis extent;
2. Click new project or re-open QGIS
3. Add hazard data
4. Add vector data
5. Voila! python error appear

# Proposed Solution
I suppose when the user re-open QGIS or click new project, the analysis extent area is set into default option (for example 'Use intersection of hazard') or set the bounding box into 0 value so user can add their hazard and exposure first and after that they must define the analysis extent.

**Comment by ismailsunni** [comment]
Hi @adissadis 
@timlinux just fixed the test. Can you test it again (after pull the latest update)

*Re-open to wait a response.

**Comment by adissadis** [comment]
hi @ismailsunni yes it already solved now. Thank you for your help!
