### ISSUE TITLE
Python error when starting QGIS

### ISSUE THREAD

**Issue by enockseth** [AIFDR/inasafe#2435]
`Couldn't load plugin inasafe due to an error when calling its classFactory() method`

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python\qgis\utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Seth/.qgis2/python/plugins\inasafe\__init__.py", line 86, in classFactory
    from safe.plugin import Plugin
  File "C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Seth/.qgis2/python/plugins\inasafe\safe\__init__.py", line 28, in 
    from safe.common.custom_logging import setup_logger
  File "C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Seth/.qgis2/python/plugins\inasafe\safe\__init__.py", line 30, in 
    setup_logger('InaSAFE')
  File "C:/Users/Seth/.qgis2/python/plugins\inasafe\safe\common\custom_logging.py", line 130, in setup_logger
    inasafe_log_path = log_file_path()
  File "C:/Users/Seth/.qgis2/python/plugins\inasafe\safe\common\utilities.py", line 793, in log_file_path
    log_temp_dir = temp_dir('logs')
  File "C:/Users/Seth/.qgis2/python/plugins\inasafe\safe\common\utilities.py", line 101, in temp_dir
    handle, filename = mkstemp()
  File "C:\PROGRA~1\QGISWI~1\apps\Python27\lib\tempfile.py", line 304, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "C:\PROGRA~1\QGISWI~1\apps\Python27\lib\tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 22] Invalid argument: 'c:\\users\\seth\\appdata\\local\\temp\\tmppcfmn4'

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.3-Wien Wien, 313a6bc
```

**Comment by ismailsunni** [comment]
Hi @enockseth 
Did you use InaSAFE from QGIS plugin repository or from github?

What's version of your OS?

Have your tried to disable the plugin, restart QGIS, and enable the plugin again?

Thanks

**Comment by timlinux** [comment]
Also it would be good to establish if ``c:\\users\\seth\\appdata\\local\\temp\\`` exists and if you have write permissions to it.

**Comment by enockseth** [comment]
HI @ismailsunn thanks for your comment and @timlinux thanks for the clue. The problem was `c:\\users\\seth\\appdata\\local\\temp\\` being corrupted. 
First time trying InaSAFE on Windows and troubles ;). 

I fixed issue by creating a new user account which has the required directory as I have no way of recovering current corrupted one. 

Best.
