### ISSUE TITLE
Unexpected keywords error when loading NetCDF raster file

### ISSUE THREAD

**Issue by uniomni** [AIFDR/inasafe#265]
I tried to load the NetCDF file 
inasafe_data/test/201208140700_Jakarta_200m_Sobek_Hypothetical_Scenario_ACCESSA.nc 
to see what needs to be changed in raster.py to support multi-band rasters.

I expected some error to do with multi-band, but instead got this keywords error:

<pre>
Traceback (most recent call last):
  File "/home/nielso/sandpit/inasafe-dev/safe_qgis/dock.py", line 705, in accept
    self.setupCalculator()
  File "/home/nielso/sandpit/inasafe-dev/safe_qgis/dock.py", line 677, in setupCalculator
    myHazardFilename, myExposureFilename = self.optimalClip()
  File "/home/nielso/sandpit/inasafe-dev/safe_qgis/dock.py", line 1057, in optimalClip
    myCellSize)
  File "/home/nielso/sandpit/inasafe-dev/safe_qgis/clipper.py", line 96, in clipLayer
    theExtraKeywords=theExtraKeywords)
  File "/home/nielso/sandpit/inasafe-dev/safe_qgis/clipper.py", line 302, in _clipRasterLayer
    verify(os.path.isfile(myKeywordsPath), myMessage)
  File "/home/nielso/sandpit/inasafe-dev/safe_qgis/safe_interface.py", line 84, in verify
    verify_util(theStatement, theMessage)
  File "/home/nielso/sandpit/inasafe-dev/safe/common/utilities.py", line 31, in verify
    raise VerificationError(message)
VerificationError: Input file to be clipped "/home/nielso/sandpit/inasafe_data/test/201208140700_Jakarta_200m_Sobek_Hypothetical_Scenario_ACCESSA.nc" does not have the expected keywords file /home/nielso/sandpit/inasafe_data/test/201208140700_Jakarta_200m_Sobek_Hypothetical_Scenario_ACCESS.keywords

Python version:
2.7.2+ (default, Oct  4 2011, 20:41:12) 
[GCC 4.6.1]

QGIS version:
1.8.0-Lisboa Lisboa, exported
</pre>

The keywords added were
<pre>
category: hazard
subcategory: flood
unit: m
title: 201208140700_Jakarta_200m_Sobek_Hypothetical_Scenario_ACCESSA
</pre>
so the error message is surprising. It'd be great to add some more info to it.

**Comment by ismailsunni** [comment]
I think we can close this since currently we don't need netCDF anymore. We can re-open if we found similar ticket.
