### ISSUE TITLE
Unhandled exception if incorrect projection encountered for density layer encountered

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#374]
This is another regression. Experienced under windows, though this is probably not a windows specific issue.

**To Replicate:**

* hazard layer: Banjir Jakarta seperti 2007
* exposure layer:  Penduduk Jakarta UTM48N
* press run

**Symptom:**

Exception caught by QGIS rather than dock resulting in a poor experience for the user.

**Traceback:**

```python
An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:\Users\Tim Sutton\.qgis\python\plugins\inasafe\safe_qgis\dock.py", line 947, in accept
    self.run()
  File "C:\Users\Tim Sutton\.qgis\python\plugins\inasafe\safe_qgis\dock.py", line 977, in run
    self.setupCalculator()
  File "C:\Users\Tim Sutton\.qgis\python\plugins\inasafe\safe_qgis\dock.py", line 845, in setupCalculator
    myHazardFilename, myExposureFilename = self.optimalClip()
  File "C:\Users\Tim Sutton\.qgis\python\plugins\inasafe\safe_qgis\dock.py", line 1962, in optimalClip
    theExtraKeywords=extraExposureKeywords)
  File "C:\Users\Tim Sutton\.qgis\python\plugins\inasafe\safe_qgis\clipper.py", line 101, in clipLayer
    theExtraKeywords=theExtraKeywords)
  File "C:\Users\Tim Sutton\.qgis\python\plugins\inasafe\safe_qgis\clipper.py", line 337, in _clipRasterLayer
    raise InvalidProjectionException(myMessage)
InvalidProjectionException: Layer C:/Users/Tim Sutton/.qgis/python/plugins/riab_test_data/Population_Jakarta_UTM48N.tif represents density but has spatial reference "+proj=utm +zone=48 +datum=WGS84 +units=m +no_defs". Density layers must be given in WGS84 geographic coordinates, so please reproject and try again. For more information, see issue https://github.com/AIFDR/inasafe/issues/123

Python version:
2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]


QGIS version:
1.8.0-Lisboa Lisboa, 6416f38

Python path: ['C:/PROGRA~2/Quantum GIS Lisboa/apps/qgis/./python', 'C:/Users/Tim Sutton/.qgis//python', 'C:/Users/Tim Sutton/.qgis//python/plugins', 'C:/PROGRA~2/Quantum GIS Lisboa/apps/qgis/./python/plugins', 'C:\\Progra~2\\Quantu~2\\apps\\Python27', 'C:\\Progra~2\\Quantu~2\\apps\\Python27\\Lib', 'C:\\Progra~2\\Quantu~2\\apps\\Python27\\libs', 'C:\\Progra~2\\Quantu~2\\apps\\qgis\\python', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\bin\\python27.zip', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\Python27\\DLLs', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\Python27\\lib', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\qgis\\bin', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\Python27', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\Users\\Tim Sutton\\.qgis\\python\\plugins\\FlightLines\\tools', 'C:\\Users\\Tim Sutton\\.qgis\\python\\plugins\\FlightLines\\tools\\gdal_modules', 'C:\\Users\\Tim Sutton\\.qgis\\python\\plugins\\inasafe', 'C:\\Users\\Tim Sutton\\.qgis\\python\\plugins\\inasafe', 'C:\\Users\\Tim Sutton\\.qgis\\python\\plugins\\inasafe', 'C:\\PROGRA~2\\Quantum GIS Lisboa\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:/Users/Tim Sutton/.qgis/python/plugins/riab_test_data']
```

**Comment by timlinux** [comment]
Can you take a look at this @cchristelis and close it if no longer relevant

**Comment by cchristelis** [comment]
No longer relevant.
