### ISSUE TITLE
Error when running Flood Impact on People

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#747]
# Problem
A wild error appears while running food impact on people using Batas Administrasi Kecamatan boundary
- People exposure is raster data (PopMap). 
- Flood is raster data (Flood_Current_Depth_Jakarta_geographic.asc).
- Aggregation layer is batas_kecamatan.shp
![err](https://f.cloud.github.com/assets/992519/1868421/86707b76-7869-11e3-8648-5ad211688e8a.PNG)

The error details:
```
An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:\Users\Akbar Gumbira\.qgis2\python\plugins\inasafe-dev\safe_qgis\widgets\dock.py", line 1365, in aggregate
    self.post_process()
  File "C:\Users\Akbar Gumbira\.qgis2\python\plugins\inasafe-dev\safe_qgis\widgets\dock.py", line 1379, in post_process
    self.postprocessor_manager.run()
  File "C:\Users\Akbar Gumbira\.qgis2\python\plugins\inasafe-dev\safe_qgis\impact_statistics\postprocessor_manager.py", line 357, in run
    value.process()
  File "C:\Users\Akbar Gumbira\.qgis2\python\plugins\inasafe-dev\safe\postprocessors\gender_postprocessor.py", line 80, in process
    self._calculate_total()
  File "C:\Users\Akbar Gumbira\.qgis2\python\plugins\inasafe-dev\safe\postprocessors\gender_postprocessor.py", line 116, in _calculate_total
    myResult = int(round(myResult))
TypeError: a float is required

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.0.1-Dufour Dufour, d94c044

Python path: ['C:/PROGRA~1/QGISDU~1/apps/qgis/./python/plugins\\processing', 'C:/PROGRA~1/QGISDU~1/apps/qgis/./python', 'C:\\Users\\Akbar Gumbira/.qgis2/python', 'C:\\Users\\Akbar Gumbira/.qgis2/python/plugins', 'C:/PROGRA~1/QGISDU~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISDU~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISDU~1\\bin', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'C:\\Users\\Akbar Gumbira\\.qgis2\\python\\plugins\\inasafe-dev', 'C:\\Users\\Akbar Gumbira\\.qgis2\\python\\plugins\\inasafe-dev\\third_party', 'C:\\PROGRA~1\\QGISDU~1\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:/Users/Akbar Gumbira/Documents/Impact merged report']
```

# System Environment
Windows 7, QGIS 2, InaSAFE Master

# CC
@timlinux @mbernasocchi

**Comment by akbargumbira** [comment]
closing this
